config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :users, only: [:show, :index] do
    get 'search_email', on: :collection, to: "users#index"
    member do
      get :following, :followers
    end
    resources :scorecards, only: [:show, :destroy]
  end

  resources :courses, only: [:show, :index] do
    get 'search', on: :collection, to: 'courses#index'
    resources :scorecards, only: [:new, :create] do
      resources :hole_scores, only: [:new, :create, :edit, :update]
    end
  end
  resources :user_connections, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :scorecards

  has_many :active_connections, class_name: "UserConnection",
                                foreign_key: "follower_id",
                                dependent: :destroy

  has_many :passive_connections, class_name: "UserConnection",
                                 foreign_key: "followed_id",
                                 dependent: :destroy

  has_many :following, through: :active_connections, source: :followed
  has_many :followers, through: :passive_connections, source: :follower

  scope :search_email, -> (name_parameter) { where(email: name_parameter.downcase) }

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def hole_scores
    result = []
    self.scorecards.each do |scorecard|
      scorecard.hole_scores.each do |holescore|
        result.push(holescore)
      end
    end

    result
  end

  def fairway_avg
    sum = 0
    count = 0
    self.scorecards.each do |scorecard|
      if scorecard.completed?
        scorecard.hole_scores.each do |holescore|
          if holescore.fairway == true
            sum += 1
          end
          count += 1
        end
      end
    end

    (1.0 * sum / count * 100).round(2)
  end

  def gir_avg
    sum = 0
    count = 0
    self.scorecards.each do |scorecard|
      if scorecard.completed?
        scorecard.hole_scores.each do |holescore|
          if holescore.green_ir == true
            sum += 1
          end
          count +=1
        end
      end
    end

    (1.0 * sum / count * 100).round(2)
  end

  def avg_score_per_game
    total = 0.0
    count = 0
    self.scorecards.each do |scorecard|
      if scorecard.completed?
        total += ((18.0 / scorecard.holes.length) * scorecard.total_score)
        count += 1
      end
    end
    (total / count).round(2)
  end

  def avg_num_of_putts
    total = 0.0
    count = 0
    self.scorecards.each do |scorecard|
      if scorecard.completed?
        total += ((18.0 / scorecard.holes.length ) * scorecard.num_of_putts)
        count += 1
      end
    end
    (total / count).round(2)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if params.key?(:search_email)
      email = params[:search_email]
      @users = User.search_email(email)
    else
      @users = []
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.followers
  end

  def following
    @user = User.find(params[:id])
    @following = @user.following
  end


end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_connections.build) do |f| %>
  <div>
    <%= hidden_field_tag :followed_id, @user.id %>
  </div>
  <%= f.submit "Follow", class: "btn btn-primary stretch-button"  %>
  <% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
<div id="follow_form">
  <% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
  <% else %>
  <%= render 'follow' %>
  <% end %>
</div>
<% end %>

app/views/users/_search_email.html.erb
<div class="search-form">
  <h3>Search Golfers:</h3>
  <div class="form-group">
  <%= form_tag users_path, method: :get do %>
    <%= text_field_tag(:search_email, params[:search_email], placeholder: 'Search users by email', class: 'form-control') %>
    <%= submit_tag("Search", class: 'btn btn-success') %>
  <% end %>
</div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_connections.find_by(followed_id: @user.id),
            html: { method: :delete}) do |f| %>
            <%= f.submit "Unfollow", class: "btn btn-primary stretch-button" %>
<% end %>

app/views/users/followers.html.erb
<% @followers.each do |follower| %>
  <h4><%= link_to follower.email, user_path(follower) %></h4>
<% end %>

app/views/users/following.html.erb
<% @following.each do |following| %>
  <h4><%= link_to following.email, user_path(following) %></h4>
<% end %>

app/views/users/index.html.erb
<%= render "search_email" %>
<div class="user-results">
<% if @users.any? %>
  <% @users.each do |user| %>
    <h4><%= link_to user.email, user_path(user.id) %></h4>
  <% end %>
<% else %>
  <h4>Sorry no golfers found under that email. Please try again.</h4>
<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <center><h1><%= @user.email %></center>
    <div class="row">
      <div class="col-xs-6">
        <h6>Average Score: <span class="avg"><%= @user.avg_score_per_game %></span> </h6>
        <h6>Number of Putts: <span class="avg"><%= @user.avg_num_of_putts %></span></h6>
      </div>
      <div class="col-xs-6">
        <h6>Fairway Count: <span class="avg"><%= @user.fairway_avg %>%</span><h6>
        <h6>GIR: <span class="avg"><%= @user.gir_avg %>%</span></h6>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <%= render 'follow_form' if user_signed_in? %>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-xs-4">
        <h6>
          <span class="follow-count"><%= @user.scorecards.count %></span>
          <span class="info-count">Rounds</span>
        </h6>
      </div>
      <div class="col-xs-4">
        <h6>
          <a href="<%= followers_user_path(@user) %>">
            <span class="follow-count">
              <%= @user.followers.count %>
            </span>
            <span class="info-count">followers</span>
          </a>
        </h6>
      </div>
      <div class="col-xs-4">
        <h6>
          <a href="<%= followers_user_path(@user) %>">
            <span class="follow-count">
              <%= @user.following.count %>
            </span>
            <span class="info-count">following</span>
          </a>
        </h6>
      </div>
    </div>
    <% @user.scorecards.each do |scorecard| %>
      <div class="row">
        <div class="col-xs-12">
          <div class="scorecard">
            <h6><%= scorecard.date_format %></h6>
            <h5><%= link_to scorecard.course_name, user_scorecard_path(@user.id, scorecard) %></h5>
            <% if ! scorecard.completed? %>
            <h6><%= link_to 'Finish scorecard', new_course_scorecard_hole_score_path(scorecard.course_id, scorecard.id) %></h6>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>