config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :users, only: [:show, :index] do
    get 'search_email', on: :collection, to: "users#index"
    member do
      get :following, :followers
    end
    resources :scorecards, only: [:show, :destroy]
  end

  resources :courses, only: [:show, :index] do
    get 'search', on: :collection, to: 'courses#index'
    resources :scorecards, only: [:new, :create] do
      resources :hole_scores, only: [:new, :create, :edit, :update]
    end
  end
  resources :user_connections, only: [:create, :destroy]
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to image_tag("onp.png"), root_path %></div>

    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <li><%= link_to "#{current_user.email}", user_path(current_user) %></li>
          <li><%= link_to "Search Golfers", users_path %><li>
          <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
        <li><form class="navbar-form">
          <div class="form-group">
            <%= render "layouts/search" %>
          </div>
        </form></li>
      </ul>



    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_search.html.erb
<%# TODO: determine why this hack works %>

<%# the presence of this form_tag seems to be %>
<%# what makes the search form after it route %>
<%# correctly when submitted %>
<div class="hidden-hack">
  <%= form_tag '/', method: :get do %>
  <% end %>
</div>

<div class="search-courses">
  <%= form_tag courses_path, method: :get do %>
    <%= text_field_tag(:search_name, params[:search_name], placeholder: 'Search Course', class: 'form-control') %>
    <%= submit_tag("Search", name: nil, class: 'btn btn-success') %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnPar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>